### ISSUE TITLE
5 millions coin pre-farmed?

### ISSUE THREAD

**Issue by tariusagi** [Spare-Network/spare-blockchain#72]
I found that you pre-farm 5 milliions coins at https://github.com/Spare-Network/spare-blockchain/blob/3599b18e71ccefd9d3842c09216ae2dc7e01b47f/spare/consensus/block_rewards.py#L43.

Is this normal? It's against your statement about not prefarming like the original Chia.

**Comment by SergeyKGoncharov** [comment]
WOW! Tariusagi, good find! Spare, give your comment

**Comment by fluorfr** [comment]
@root-spare Normal ?

**Comment by GTANAdam** [comment]
Well, this is going to be a problem.

**Comment by PC101guy** [comment]
so the devs wanna make a few easy billion, is that so wrong? wheres the harm in it, i see none, were crying over spilled milk here.   we all get rich together thats how it is.

**Comment by buglantiss** [comment]
We demand an answer in no time!

**Comment by coint8801** [comment]
We have to be understanding.
Coin or cash is required to be listed on the exchange.
You guys don't want to be listed on the exchange?

**Comment by fluorfr** [comment]
answer ?

**Comment by ahnguyen17** [comment]
noone is going to take this fork seriously without an answer.

**Comment by petrkr** [comment]
Anyone took any of fork seriously?
Every fork is just copy&search&replace&paste from chia codebase. Everyone just aim for pre-farmed in vision of "lambo soon". That is why they prefarm, that is why they do not response here.. They are not care about make good coin, they are about catch chia-boom-wave and earn something too.. Because "regular peoples" (not experienced in crypto) will mine all forks "becase we can and cost nothing".
