### ISSUE TITLE
Wallet Not Synced

### ISSUE THREAD

**Issue by cryptoguru2040** [Spare-Network/spare-blockchain#97]
I have been running Spare Coin Full Node for more than 5 days. Everything seems to be working and synced. However, the Wallet is not synced at all. Even further, my estimated winning time was few hours few days ago and it is sitting at "a day" now but nothing has dropped so far. Is wallet issue related to farming as well?

**Comment by olgyan93btc** [comment]
i have the same problem

**Comment by ghost** [comment]
I had a similar issue with my Mac.  Everything seemed to be working fine with no warnings in the log, but did not win any coins.  In the beginning it was showing "hour" or "2 hours" but didn't win any for 5 days.  I tried running in Ubuntu and Windows but still didn't win any.  
Couple of days ago, I decided to reinstall the App in my Mac after deleting all the files in the directories that were seemed to be created by Spare Blockchain such as ".spare-blockchian", "spare-blockchain" and ".npm".  After the reinstallation, it finally started to win coins with frequencies very close to what is shown in "Estimated Time to Win".  I don't know what made the difference but it's running fine now.  
I wish I had done this earlier because now the estimated time to win is like 9 hours with 300TB plot files.

**Comment by root-spare** [comment]
Hello, @rkandel , @olgyan93btc @KayCreative .

We have fixed the DNS introducer and now you shouldn't have a sync problem anymore!
